name: ci

on:
  push:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: make build

      - name: Build the Docker image
        run: make push
        if: github.ref_name == 'master'
  docker-push:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Build the Docker image
        run: make push
        if: github.ref_name == 'master'
